dnfzf: dynamically reload the script
- update formatting
- s/printf/echo -e/

diff --git a/DNFzf b/DNFzf
--- a/DNFzf
+++ b/DNFzf
@@ -1,24 +1,25 @@
 #!/usr/bin/env bash
-# Colors                                 # Base Commands
+
 declare blu red grn ylw cyn rst bld mgn QRY PRVW QRY_PRFX QRY_SFFX AWK_VAR QRY_READ DNFZF_DIR
-blu="$(tput setaf 4)"
-QRY="dnf --cacheonly --quiet repoquery "
 red="$(tput setaf 1)"
-PRVW="dnf --cacheonly --quiet --color=always info"
 grn="$(tput setaf 2)"
-QRY_PRFX='  '
 ylw="$(tput setaf 3)"
-QRY_SFFX=' > '
-cyn="$(tput setaf 6)"
-QRY_READ="read -rs -p $'\n${blu}$(tput bold)Press any key to continue...${rst}' && printf '\n'" #bold text isnt working so i didn't use variable
+blu="$(tput setaf 4)"
 mgn="$(tput setaf 5)"
-AWK_VAR="awk -v red=$red -v grn=$grn -v ylw=$ylw -v blu=$blu -v mgn=$mgn -v cyn=$cyn -v rst=\$(tput sgr0) -v bld=\$(tput bold)"
+cyn="$(tput setaf 6)"
 rst="$(tput sgr0)"
 bld="$(tput bold)"
 
+QRY="dnf --cacheonly --quiet repoquery "
+PRVW="dnf --cacheonly --quiet --color=always info"
+QRY_PRFX='  '
+QRY_SFFX=' > '
+QRY_READ="read -rs -p $'\n${blu}$(tput bold)Press any key to continue...${rst}' && echo -e '\n'" #bold text isnt working so i didn't use variable
+AWK_VAR="awk -v red=$red -v grn=$grn -v ylw=$ylw -v blu=$blu -v mgn=$mgn -v cyn=$cyn -v rst=\$(tput sgr0) -v bld=\$(tput bold)"
+
 basename="$(basename "$0")"
 if ! hash fzf &>/dev/null; then
-	printf "${bld}${red}Error:${rst}${ylw} Missing dependency\n${bld}${cyn}Fzf${rst} is required to use %s.\n" "${bld}${blu}${basename}" >&2
+	echo -e "${bld}${red}Error:${rst}${ylw} Missing dependency\n${bld}${cyn}Fzf${rst} is required to use %s.\n" "${bld}${blu}${basename}" >&2
 	exit 64
 fi
 DNFZF_DIR="$HOME/.cache/fzf/${basename}"
@@ -73,29 +74,27 @@ SHOW_HELP=$(
 		    ${blu}${bld}Alt-d       ${rst}Distro Sync (synchronize package/s)
 
 		    ${blu}${bld}Ctrl-h      ${rst}${mgn}History mode
-		    ${blu}${bld}Ctrl-z      ${rst}Undo History 
+		    ${blu}${bld}Ctrl-z      ${rst}Undo History
 		    ${blu}${bld}Ctrl-y      ${rst}Redo History
 
 		    ${blu}${bld}Ctrl-a      ${rst}Select all
-		    ${blu}${bld}Ctrl-e      ${rst}Edit/configure DNF 
+		    ${blu}${bld}Ctrl-e      ${rst}Edit/configure DNF
 		    ${blu}${bld}Delete      ${rst}Delete expired packages cache
 		    ${blu}${bld}Delete      ${rst}And ${blu}${basename}${rst} - install cache
 
-		    ${blu}${bld}Alt-t       ${rst}Topgrade (upgrade everything)
-
 		    ${blu}${bld}Enter       ${rst}Confirm selection or View History
-		    ${blu}${bld}Tab         ${rst}Mark package ()
-		    ${blu}${bld}Shift-Tab   ${rst}Unmark package
+		    ${blu}${bld}Tab         ${rst}Select/Mark package/s ()
+		    ${blu}${bld}Shift-Tab   ${rst}Unselect/Unmark package/s
 
 		    ${blu}${bld}Alt-?       ${rst}Help (this page)
-		    ${blu}${bld}ESC         ${rst}Quit                          
+		    ${blu}${bld}ESC         ${rst}Quit
 	EOF
 )
 
 declare tmp_file
 if tmp_file="$(mktemp --tmpdir "${basename}".XXXXXX)"; then
-	printf 'in' >"${tmp_file}" && SHELL='/bin/bash' \
-		FZF_DEFAULT_COMMAND="cat < \"${DNFZF_DIR}/install\" || ${INS_QRYS} > \"${DNFZF_DIR}/install\";" \
+	echo -e 'in' >"${tmp_file}" && SHELL='/bin/bash' \
+		FZF_DEFAULT_COMMAND="cat < \"${DNFZF_DIR}/install\" || ${INS_QRYS} > \"${DNFZF_DIR}/install\" && cat < \"${DNFZF_DIR}/install\" ;" \
 		fzf --ansi --multi --tiebreak=begin --query="$*" --sync --no-separator \
 		--preview="${INS_CMD_PRVW} {1} || ${INS_CLR_PRVW}" \
 		--preview-window "50%,<50(up,60%,border-rounded)" \
@@ -111,25 +110,24 @@ if tmp_file="$(mktemp --tmpdir "${basename}".XXXXXX)"; then
 	elif grep -q 'hist' \"${tmp_file}\"; then 
 	    ${HISTORY_CMD_PRVW} | less;
 	fi;)" \
-		--bind "alt-i:reload(cat < \"${DNFZF_DIR}/install\")+change-preview(${INS_CMD_PRVW} {1} | ${INS_CLR_PRVW})+change-prompt(${INS_PRMPT})+execute-silent(printf 'in' > \"${tmp_file}\")+first" \
-		--bind "alt-r:reload(${RMV_QRYS})+change-preview(${RMV_CMD_PRVW} {1} | ${RMV_CLR_PRVW})+change-prompt(${RMV_PRMPT})+execute-silent(printf 'rm' > \"${tmp_file}\")+first" \
-		--bind "alt-e:reload(${RUI_QRYS})+change-preview(${RUI_CMD_PRVW} {1} | ${RUI_CLR_PRVW})+change-prompt(${RUI_PRMPT})+execute-silent(printf 'rm' > \"${tmp_file}\")+first" \
-		--bind "alt-u:reload(${UPD_QRYS})+change-preview(${UPD_CMD_PRVW} {1})+change-prompt(${UPD_PRMPT})+execute-silent(printf 'up' > \"${tmp_file}\")+first" \
-		--bind "ctrl-h:reload($HISTORY)+change-prompt(  History > )+change-preview($HISTORY_CMD_PRVW)+execute-silent(printf 'hist' > \"${tmp_file}\")+first" \
+		--bind "alt-i:reload(cat < \"${DNFZF_DIR}/install\")+change-preview(${INS_CMD_PRVW} {1} | ${INS_CLR_PRVW})+change-prompt(${INS_PRMPT})+execute-silent(echo -e 'in' > \"${tmp_file}\")+first" \
+		--bind "alt-r:reload(${RMV_QRYS})+change-preview(${RMV_CMD_PRVW} {1} | ${RMV_CLR_PRVW})+change-prompt(${RMV_PRMPT})+execute-silent(echo -e 'rm' > \"${tmp_file}\")+first" \
+		--bind "alt-e:reload(${RUI_QRYS})+change-preview(${RUI_CMD_PRVW} {1} | ${RUI_CLR_PRVW})+change-prompt(${RUI_PRMPT})+execute-silent(echo -e 'rm' > \"${tmp_file}\")+first" \
+		--bind "alt-u:reload(${UPD_QRYS})+change-preview(${UPD_CMD_PRVW} {1})+change-prompt(${UPD_PRMPT})+execute-silent(echo -e 'up' > \"${tmp_file}\")+first" \
+		--bind "ctrl-h:reload($HISTORY)+change-prompt(  History > )+change-preview($HISTORY_CMD_PRVW)+execute-silent(echo -e 'hist' > \"${tmp_file}\")+first" \
 		--bind "ctrl-z:execute(sudo dnf history undo {1}; ${QRY_READ})" \
 		--bind "ctrl-y:execute(sudo dnf history redo {1}; ${QRY_READ})" \
-		--bind "alt-t:execute(sudo dnf makecache;topgrade; ${QRY_READ})" \
 		--bind "alt-m:execute(sudo dnf makecache; ${QRY_READ})" \
 		--bind "alt-a:execute(sudo dnf autoremove;${QRY_READ})" \
 		--bind "ctrl-e:execute(sudo \$EDITOR /etc/dnf/dnf.conf > /dev/tty)" \
-		--bind "del:execute(dnf clean expire-cache packages && rm -f \"${DNFZF_DIR}/install\"; echo -e '${blu}${basename} cache has been deleted\n'; ${QRY_READ})" \
+		--bind "del:execute(dnf clean expire-cache packages && rm -rf \"${DNFZF_DIR}/install\"; echo -e '${blu}${basename} cache has been deleted\n'; ${QRY_READ})" \
 		--bind "alt-d:execute(sudo dnf distrosync;${QRY_READ})" \
-		--bind "alt-?:preview(printf '${SHOW_HELP}')" \
+		--bind "alt-?:preview(echo -e '${SHOW_HELP}')" \
 		--bind "alt-/:toggle-preview-wrap" \
 		--bind "ctrl-/:execute(${PRVW} {+1} | less )" \
 		--bind "ctrl-a:select-all"
 	rm -f "${tmp_file}" &>/dev/null
 else
-	printf "${bld}${red}Error:${rst} Failed to create tmp file." >&2
+	echo -e "${bld}${red}Error:${rst} Failed to create tmp file." >&2
 	exit 65
 fi
