lofi: refactor

diff --git a/lofi b/lofi
--- a/lofi
+++ b/lofi
@@ -1,9 +1,6 @@
 #!/usr/bin/env bash
 
-if ! command -v mpv &>/dev/null; then
-	echo "Error: mpv is not installed. Please install it before running this script."
-	exit 1
-fi
+command -v mpv &>/dev/null || { echo "Error: mpv is not installed." && exit 1; }
 
 # should work unless the link has been changed/ended/taken down...
 declare -A urls=(
@@ -28,61 +25,57 @@ Play/Stream lofi music audio, and nothing else
                           - Amberol (probably)
 
 Options:
-  -s, --study      Play lofi radio beats to relax/study music.
-  -c, --chill      Play lofi radio beats sleeps/chill music.
-  -g, --game       Play lofi synthwave radio beats to chill/game music.
-  -f, --fcc        Play freeCodeCamp Code Radio.
-  -r, --random     Play a random station url (study, chilll, game, fcc).
-  -v, --video      Play with video (default: none, no video for fcc).
-  -h, --help       Display this help message.
+  -s, --study, relax      Play lofi radio beats to relax/study music.
+  -c, --chill, sleep      Play lofi radio beats sleeps/chill music.
+  -g, --game, synthwave   Play lofi synthwave radio beats to chill/game music.
+  -f, --fcc, fcc, code    Play freeCodeCamp Code Radio.
+  -r, --random            Play a random station URL (study, chill, game, fcc).
+  -v, --video             Play with video (default: none, no video for fcc).
+  -h, --help              Display this help message.
 EOF
+}
+
+set_station() { station_name=$1 && url=${urls[$station_name]}; }
+set_station_based_on_time_of_the_day() {
+	hour=$(date +%_H)
+	if ((hour >= 22 && hour < 6)); then
+		set_station "chill"
+	elif ((hour >= 6 && hour < 12)); then
+		set_station "study"
+	elif ((hour >= 18 && hour < 22)); then
+		set_station "game"
+	else
+		set_station "fcc"
+	fi
 }
 
 main() {
 	local url
 	local video=false
-	# auto play if there's no arg provided based on time of the day
 	if [[ $# -eq 0 ]]; then
-		hour=$(date +%_H)
-		if ((hour >= 22 && hour < 6)); then
-			url=${urls["chill"]}
-			station_name="chill"
-		elif ((hour >= 6 && hour < 12)); then
-			url=${urls["study"]}
-			station_name="study"
-		elif ((hour >= 18 && hour < 22)); then
-			url=${urls["game"]}
-			station_name="game"
-		else
-			url=${urls["fcc"]}
-			station_name="fcc"
-		fi
+		set_station_based_on_time_of_the_day
 	else
 		while [[ $# -gt 0 ]]; do
 			case $1 in
-			-s | --study | study)
-				url=${urls["study"]}
-				station_name="study"
+			-s | --study | relax | study)
+				set_station "study"
 				shift
 				;;
-			-c | --chill | chill)
-				url=${urls["chill"]}
-				station_name="chill"
+			-c | --chill | sleep | chill)
+				set_station "chill"
 				shift
 				;;
-			-g | --game | game)
-				url=${urls["game"]}
-				station_name="game"
+			-g | --game | synthwave | game)
+				set_station "game"
 				shift
 				;;
-			-f | --fcc | fcc)
-				url=${urls["fcc"]}
-				station_name="fcc"
+			-f | --fcc | code | fcc)
+				set_station "fcc"
 				shift
 				;;
 			-r | --random)
-				station_name=$(shuf -n 1 -e "${!urls[@]}")
-				url=${urls[$station_name]}
+				random_station_name=$(shuf -n 1 -e "${!urls[@]}")
+				set_station "$random_station_name"
 				shift
 				;;
 			-v | --video)
